### ISSUE TITLE
Doesn't work in 3.0.75 RC3.

### ISSUE THREAD

**Issue by Yuan-Yggdrasil** [Richienb/synergy-serial#34]
Synergy release notes
3.0.75 RC3

Bug fixes

• Fix ipc error when opening external applications
• Fix error when using login to setup Synergy 3
• Fix Wayland message url
• Fix "expressions.tomorrow" is not a function
• Fix error reporting is showed as disabled when enabled

Enhancements

• Improve serial key comparisons
• Improve performance of the build-in log view
• More error reporting
• Improved context for errors
• Add simpler stack traces for errors
• Leave serial key in manual entered serial key

**Comment by Richienb** [comment]
I wonder whether this PR has the solution? https://github.com/Richienb/synergy-serial/pull/33

**Comment by Frambooisier** [comment]
so it's not working on version 3?

**Comment by RattanCandy** [comment]
> so it's not working on version 3?

rc2 works, but not the rc3 version.

**Comment by saadndm** [comment]
> I wonder whether this PR has the solution? #33

Yes #33 has fixed it, not sure why the PR was closed

**Comment by Marcus112-CS** [comment]
> > so it's not working on version 3?
> 
> rc2 works, but not the rc3 version.

Could you provide a download link for rc2 version ? Official website couldn't download this version without an account
